---
################################################################################
#
#   CONFIGURATIONS
#
#   - Nest keys where appropriate, and sort alphabetically for easier parsing.
#
################################################################################
IPs:
  node0: 47.74.86.40
  node1: 8.219.254.203
  node2: 8.211.128.55
  node3: 8.213.137.171
peers_p2p_port:
  node0: 9000
  node1: 9000
  node2: 9000
  node3: 9000
max_pool: 20
log_level: 3
batch_size: 200
round: 80
faulty_number: 0
protocol: qcdag