batch_size: 100
cluster_ips:
    node0: 192.168.5.10
    node1: 192.168.5.11
    node2: 192.168.5.12
    node3: 192.168.5.13
cluster_pubkeyed:
    node0: e9b43c3ad1e28fef4819806670256f2954977a72b731ec54e19b4af292aca8fd
    node1: ede4fe8d2e6816effc37caf7ae033dcc272febdd1b63baaa2d6a8b7ffc8b74bd
    node2: bac25764d1882657c96699d983d98cb8f9710ad70b699fa81f819af7fd6a00e8
    node3: d2bc035e1f319ab93909addb22dd59f9ce5fa156dcc64a3463321aad8ee67f98
is_faulty: 1
log_level: 2
max_pool: 10
name: node0
peers_p2p_port:
    node0: 9000
    node1: 9000
    node2: 9000
    node3: 9000
privkeyed: d7262e9c68c58a8c31ddc97e0ad4ee9e377a1c088bb3f1e64020b95ef00d863de9b43c3ad1e28fef4819806670256f2954977a72b731ec54e19b4af292aca8fd
protocol: fork1
round: 10
tspubkey: 7b22426173654279746573223a224c73796b527639765055304478323662584855764b4c77337332544c4261784b4e2b737934634d6b575843504a54687663736c474b34465a66575775494a4c45755865534656334e71744d72696d335546354a54544332784476556a4f772f6a6c6975653571533777725739344270553831453951742b584c684b504d6238534a303558522b6a4b2b737733467379476d6474357369384f542f5043506f6d50615551676f3734776836553d222c22436f6d6d69744279746573223a5b2241416a305a54394e6371673266366f584f6443517a684a57795071662f38535661384b6e45504a4d7550594a687832683962766b74336f5457696e627245744c724a4c4d6b67795347476f4543554d316c4d315277572b473272564f4c656244333937743662366466672b4778736a37733872626142766d4464396d632f355546304e3969314a634b6972516668424431624242396b623872614a2f6569536461345569776e31627264593d222c226a5858467a474246674b366a6b4d6f6f59594c2f5338643462464433544f566c6f6a7a6f4f51685a426439454645555956736f66686c656f766d5065514247746e7153737173706c4f4e72582f433869446664483156574868484f4936597867664d74593334376c5a79516176734142746a3558537970586853516d61317432666459767a46552b7073765a4b52695654472b50794b4b4d5552492b325457565a51717575772f2f67756b3d222c225850757262725239574f52394f2b4a5058787a577174774a74774d7735663746566930627056344d4b35434b7449376e6179714a477a7266774261696871472b704b396d4a2b6c524d716f4866315378577066704878785235436870323764516c6536304b4f31477a7143395a745548673677496b564a304a6c79436633426b4245775469566447586f324d686b55784e564153376c58384e706c4d447863544a7661783645635733694d3d225d7d0a
tsshare: 7b2249223a302c2242696e617279223a224d4b5972366a593878414f7679487a636f444c38462f5761785374526e6d44394664742b727a563139564d3d227d0a
